### ISSUE TITLE
Directory `Data/` missing ?

### ISSUE THREAD

**Issue by lgautier** [Jverma/NetworkxD3#1]
`setup.py` is mentioning data in `Data/*.txt` but the directory appears missing from the repository.

`git add Data/*.txt` before `git commit` and `git push` in the root directory of the original clone might be a way to fix this. An another way would be to remove `Data/*.txt` from `setup.py`.

**Comment by Jverma** [comment]
Thanks @lgautier. 
I just removed the `Data/*.txt` from the `setup.py`
